//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.0.
// 
namespace BooksAnyplace.net.xmethods.www1 {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CurrencyExchangeBinding", Namespace="http://www.xmethods.net/sd/CurrencyExchangeService.wsdl")]
    public class CurrencyExchangeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public CurrencyExchangeService() {
            this.Url = "http://services.xmethods.net:80/soap";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="urn:xmethods-CurrencyExchange", ResponseNamespace="urn:xmethods-CurrencyExchange")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public System.Single getRate(string country1, string country2) {
            object[] results = this.Invoke("getRate", new object[] {
                        country1,
                        country2});
            return ((System.Single)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRate(string country1, string country2, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRate", new object[] {
                        country1,
                        country2}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Single EndgetRate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Single)(results[0]));
        }
    }
}
