//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.288
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3705.288.
// 
namespace People_Anyplace.net.serviceobjects.ws {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GeoPhoneSoap", Namespace="http://www.serviceobjects.com/")]
    public class GeoPhone : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public GeoPhone() {
            this.Url = "http://ws.serviceobjects.net/gp/GeoPhone.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.serviceobjects.com/GetPhoneInfo", RequestNamespace="http://www.serviceobjects.com/", ResponseNamespace="http://www.serviceobjects.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PhoneInfo GetPhoneInfo(string PhoneNumber, string LicenseKey) {
            object[] results = this.Invoke("GetPhoneInfo", new object[] {
                        PhoneNumber,
                        LicenseKey});
            return ((PhoneInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPhoneInfo(string PhoneNumber, string LicenseKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPhoneInfo", new object[] {
                        PhoneNumber,
                        LicenseKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public PhoneInfo EndGetPhoneInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PhoneInfo)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.serviceobjects.com/")]
    public class PhoneInfo {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Provider[] Providers;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Contact[] Contacts;
        
        /// <remarks/>
        public string Error;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.serviceobjects.com/")]
    public class Provider {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string URL;
        
        /// <remarks/>
        public string City;
        
        /// <remarks/>
        public string State;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.serviceobjects.com/")]
    public class Contact {
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public string Address;
        
        /// <remarks/>
        public string City;
        
        /// <remarks/>
        public string State;
        
        /// <remarks/>
        public string Zip;
    }
}
