//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.12
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.12.
// 
namespace People_Anyplace.com.esri.arcweb {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IPlaceFinderSample", Namespace="http://arcweb.esri.com/PlaceFinderSample")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Location))]
    public class PlaceFinderSample : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public PlaceFinderSample() {
            this.Url = "http://arcweb.esri.com:80/services/v1/PlaceFinderSample";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("getVersion", RequestNamespace="http://arcweb.esri.com/PlaceFinderSample", ResponseNamespace="http://arcweb.esri.com/PlaceFinderSample")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string getVersion() {
            object[] results = this.Invoke("getVersion", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetVersion(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getVersion", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetVersion(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("findPlace", RequestNamespace="http://arcweb.esri.com/PlaceFinderSample", ResponseNamespace="http://arcweb.esri.com/PlaceFinderSample")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public LocationInfo findPlace(string placeName) {
            object[] results = this.Invoke("findPlace", new object[] {
                        placeName});
            return ((LocationInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfindPlace(string placeName, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("findPlace", new object[] {
                        placeName}, callback, asyncState);
        }
        
        /// <remarks/>
        public LocationInfo EndfindPlace(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((LocationInfo)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="findPlace1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("findPlace", RequestNamespace="http://arcweb.esri.com/PlaceFinderSample", ResponseNamespace="http://arcweb.esri.com/PlaceFinderSample")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public LocationInfo findPlace(string placeName, PlaceFinderOptions placeFinderOptions) {
            object[] results = this.Invoke("findPlace1", new object[] {
                        placeName,
                        placeFinderOptions});
            return ((LocationInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfindPlace1(string placeName, PlaceFinderOptions placeFinderOptions, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("findPlace1", new object[] {
                        placeName,
                        placeFinderOptions}, callback, asyncState);
        }
        
        /// <remarks/>
        public LocationInfo EndfindPlace1(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((LocationInfo)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("LocationInfo", "http://www.themindelectric.com/package/com.esri.is.services.common/")]
    public class LocationInfo {
        
        /// <remarks/>
        public string matchType;
        
        /// <remarks/>
        public Location[] candidates;
        
        /// <remarks/>
        public bool hasMore;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("Location", "http://www.themindelectric.com/package/com.esri.is.services.common/")]
    public class Location {
        
        /// <remarks/>
        public System.Double x;
        
        /// <remarks/>
        public System.Double y;
        
        /// <remarks/>
        public string description1;
        
        /// <remarks/>
        public string description2;
        
        /// <remarks/>
        public System.Double score;
        
        /// <remarks/>
        public string matchType;
        
        /// <remarks/>
        public string type;
        
        /// <remarks/>
        public Envelope locationExtent;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("Envelope", "http://www.themindelectric.com/package/com.esri.is.services.common.v1.geom/")]
    public class Envelope {
        
        /// <remarks/>
        public System.Double minx;
        
        /// <remarks/>
        public System.Double miny;
        
        /// <remarks/>
        public System.Double maxx;
        
        /// <remarks/>
        public System.Double maxy;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapTypeAttribute("PlaceFinderOptions", "http://www.themindelectric.com/package/com.esri.is.services.glue.v1.placefinder/")]
    public class PlaceFinderOptions {
        
        /// <remarks/>
        public string dataSource;
        
        /// <remarks/>
        public string filterType;
        
        /// <remarks/>
        public Envelope filterEnvelope;
        
        /// <remarks/>
        public int startIndex;
        
        /// <remarks/>
        public int count;
    }
}
