//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace People_Anyplace.net.serviceobjects.ws2 {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DOTSYellowPagesSoap", Namespace="http://www.serviceobjects.com/")]
    public class DOTSYellowPages : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public DOTSYellowPages() {
            this.Url = "http://ws2.serviceobjects.net/yp/YellowPages.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.serviceobjects.com/GetYPListingsByCategoryID", RequestNamespace="http://www.serviceobjects.com/", ResponseNamespace="http://www.serviceobjects.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Listings GetYPListingsByCategoryID(int CategoryID, string PostalCode, int Radius, string LicenseKey) {
            object[] results = this.Invoke("GetYPListingsByCategoryID", new object[] {
                        CategoryID,
                        PostalCode,
                        Radius,
                        LicenseKey});
            return ((Listings)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetYPListingsByCategoryID(int CategoryID, string PostalCode, int Radius, string LicenseKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetYPListingsByCategoryID", new object[] {
                        CategoryID,
                        PostalCode,
                        Radius,
                        LicenseKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public Listings EndGetYPListingsByCategoryID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Listings)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.serviceobjects.com/GetAllYPCategories", RequestNamespace="http://www.serviceobjects.com/", ResponseNamespace="http://www.serviceobjects.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Categories GetAllYPCategories(string LicenseKey) {
            object[] results = this.Invoke("GetAllYPCategories", new object[] {
                        LicenseKey});
            return ((Categories)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAllYPCategories(string LicenseKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAllYPCategories", new object[] {
                        LicenseKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public Categories EndGetAllYPCategories(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Categories)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.serviceobjects.com/GetYPCategoryByID", RequestNamespace="http://www.serviceobjects.com/", ResponseNamespace="http://www.serviceobjects.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Category GetYPCategoryByID(int CategoryID, string LicenseKey) {
            object[] results = this.Invoke("GetYPCategoryByID", new object[] {
                        CategoryID,
                        LicenseKey});
            return ((Category)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetYPCategoryByID(int CategoryID, string LicenseKey, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetYPCategoryByID", new object[] {
                        CategoryID,
                        LicenseKey}, callback, asyncState);
        }
        
        /// <remarks/>
        public Category EndGetYPCategoryByID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Category)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.serviceobjects.com/")]
    public class Listings {
        
        /// <remarks/>
        public Err Error;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Listing")]
        public Listing[] Listing;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.serviceobjects.com/")]
    public class Err {
        
        /// <remarks/>
        public string Desc;
        
        /// <remarks/>
        public string Number;
        
        /// <remarks/>
        public string Location;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.serviceobjects.com/")]
    public class Category {
        
        /// <remarks/>
        public int CategoryID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public Err Error;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.serviceobjects.com/")]
    public class Categories {
        
        /// <remarks/>
        public Err Error;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Category")]
        public Category[] Category;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.serviceobjects.com/")]
    public class Listing {
        
        /// <remarks/>
        public string Category;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public string CompanyName;
        
        /// <remarks/>
        public string Address;
        
        /// <remarks/>
        public string City;
        
        /// <remarks/>
        public string State;
        
        /// <remarks/>
        public string Zip;
        
        /// <remarks/>
        public string Phone;
        
        /// <remarks/>
        public System.Decimal Latitude;
        
        /// <remarks/>
        public System.Decimal Longitude;
    }
}
